// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: api/reservation/v1/reservation.proto

package reservationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_api_reservation_v1_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ReserveRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ReserveRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_reservation_v1_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_reservation_v1_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_reservation_v1_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Operation) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Operation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type PublicError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicError) Reset() {
	*x = PublicError{}
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicError) ProtoMessage() {}

func (x *PublicError) ProtoReflect() protoreflect.Message {
	mi := &file_api_reservation_v1_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicError.ProtoReflect.Descriptor instead.
func (*PublicError) Descriptor() ([]byte, []int) {
	return file_api_reservation_v1_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *PublicError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_api_reservation_v1_reservation_proto protoreflect.FileDescriptor

const file_api_reservation_v1_reservation_proto_rawDesc = "" +
	"\n" +
	"$api/reservation/v1/reservation.proto\x12\x0ereservation.v1\"p\n" +
	"\x0eReserveRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantityJ\x04\b\x04\x10\x05R\asubject\"/\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"#\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x81\x01\n" +
	"\tOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05stateJ\x04\b\x05\x10\x06R\asubject\"!\n" +
	"\vPublicError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code2\xda\x01\n" +
	"\x12ReservationService\x12D\n" +
	"\aReserve\x12\x1e.reservation.v1.ReserveRequest\x1a\x19.reservation.v1.Operation\x12<\n" +
	"\x03Get\x12\x1a.reservation.v1.GetRequest\x1a\x19.reservation.v1.Operation\x12@\n" +
	"\x04List\x12\x1b.reservation.v1.ListRequest\x1a\x19.reservation.v1.Operation0\x01BBZ@example.com/reservation-service/api/reservation/v1;reservationv1b\x06proto3"

var (
	file_api_reservation_v1_reservation_proto_rawDescOnce sync.Once
	file_api_reservation_v1_reservation_proto_rawDescData []byte
)

func file_api_reservation_v1_reservation_proto_rawDescGZIP() []byte {
	file_api_reservation_v1_reservation_proto_rawDescOnce.Do(func() {
		file_api_reservation_v1_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_reservation_v1_reservation_proto_rawDesc), len(file_api_reservation_v1_reservation_proto_rawDesc)))
	})
	return file_api_reservation_v1_reservation_proto_rawDescData
}

var file_api_reservation_v1_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_reservation_v1_reservation_proto_goTypes = []any{
	(*ReserveRequest)(nil), // 0: reservation.v1.ReserveRequest
	(*GetRequest)(nil),     // 1: reservation.v1.GetRequest
	(*ListRequest)(nil),    // 2: reservation.v1.ListRequest
	(*Operation)(nil),      // 3: reservation.v1.Operation
	(*PublicError)(nil),    // 4: reservation.v1.PublicError
}
var file_api_reservation_v1_reservation_proto_depIdxs = []int32{
	0, // 0: reservation.v1.ReservationService.Reserve:input_type -> reservation.v1.ReserveRequest
	1, // 1: reservation.v1.ReservationService.Get:input_type -> reservation.v1.GetRequest
	2, // 2: reservation.v1.ReservationService.List:input_type -> reservation.v1.ListRequest
	3, // 3: reservation.v1.ReservationService.Reserve:output_type -> reservation.v1.Operation
	3, // 4: reservation.v1.ReservationService.Get:output_type -> reservation.v1.Operation
	3, // 5: reservation.v1.ReservationService.List:output_type -> reservation.v1.Operation
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_reservation_v1_reservation_proto_init() }
func file_api_reservation_v1_reservation_proto_init() {
	if File_api_reservation_v1_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_reservation_v1_reservation_proto_rawDesc), len(file_api_reservation_v1_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_reservation_v1_reservation_proto_goTypes,
		DependencyIndexes: file_api_reservation_v1_reservation_proto_depIdxs,
		MessageInfos:      file_api_reservation_v1_reservation_proto_msgTypes,
	}.Build()
	File_api_reservation_v1_reservation_proto = out.File
	file_api_reservation_v1_reservation_proto_goTypes = nil
	file_api_reservation_v1_reservation_proto_depIdxs = nil
}
