import { mkdirSync, writeFileSync, existsSync, readFileSync, unlinkSync } from 'node:fs'
import { dirname, join } from 'node:path'
import matter from 'gray-matter'
import { site } from '../site.config.mjs'
import { readTopics, taxonomy, paths, sourceUrl, registries, kinds, validateOutputRoutes } from './knowledge.mjs'
import { domainBridges, experimentTitles } from '../content/domain-bridges.mjs'
import { categoryGuides } from '../content/category-guides.mjs'
import { domainGuides } from '../content/domain-guides.mjs'
import { plannedPaths } from '../content/paths.mjs'
import { groupExperimentRecords } from './experiment-records.mjs'
const root=process.cwd()
const pageAnchors=JSON.parse(readFileSync(join(root,'content/page-anchors.json'),'utf8'))
const page=(source,title,description,body)=>{
  const path=join(root,'docs',source);mkdirSync(dirname(path),{recursive:true})
  let text=`# ${title}\n\n${body.trim()}\n`
  for(const anchor of pageAnchors[source]||[]){if(text.split(anchor.before).length!==2)throw Error(`Ambiguous semantic legacy anchor ${source}#${anchor.id}`);text=text.replace(anchor.before,`<div id="${anchor.id}" class="legacy-anchor" aria-hidden="true"></div>\n\n${anchor.before}`)}
  const value=matter.stringify(text,{title,description,prev:false,next:false,lastUpdated:false,generated:true,search:false},{lineWidth:-1})
  if(!existsSync(path)||readFileSync(path,'utf8')!==value)writeFileSync(path,value)
}
const link=t=>`[${t.title}](${t.url})`
const list=topics=>topics.map(t=>`- ${link(t)}：${t.description}`).join('\n')
export function generateViews(){
  const topics=readTopics(), registry=registries(), domainLink=d=>`[${d.title}](/knowledge/${d.id}/)`,categoryUrl=(d,c)=>`/knowledge/${d.id}/${c.id}/`
  validateOutputRoutes(topics)
  page('index.md','后端开发知识库','从领域目录查机制，沿学习路线建立联系，用源码和实验检验判断。',`这里围绕一个问题组织内容：**行为为什么这样发生，条件变化后应当怎样判断。** 从领域目录找具体机制；需要连成一条主线时，再选择有目标的学习路线。\n\n- [按领域查知识](/knowledge/)：从分类进入机制、源码、模式与比较\n- [按目标选择路线](/paths/)：看阅读准备、阅读目的和阶段任务\n- [从场景或故障进入](/cases/)：先界定问题，再回到相关机制\n\n## 知识领域\n\n${taxonomy.map(d=>`- ${domainLink(d)}${topics.some(t=>t.domain===d.id)?'':'（领域导读已上线，专题文章待补充）'}：${d.summary}`).join('\n')}\n\n## 怎样使用一篇文章\n\n先读开篇问题和适用范围，再沿图与具体输入解释状态变化。源码页把接口合同与固定版本实现分开；模式页比较约束、代价和简单替代。实验详情放在可展开附录，运行通过只支持它明确覆盖的条件。\n\n想检验理解，可以在[复习与推理](/resources/review.html)改变一个条件再预测结果；需要查具体实现，进入[源码阅读](/resources/source-reading.html)。未写内容集中标为规划，不会生成空知识页。`)
  page('knowledge/index.md','知识目录','九个领域按分类下钻到稳定知识点，规划与可读内容明确分开。',`目录回答知识属于哪里，路线回答为了某个目标怎样读。同一篇正文可以被多条路线、源码专题和场景引用。\n\n${taxonomy.map(d=>{const own=topics.filter(t=>t.domain===d.id);return `## ${d.title}\n\n${d.summary}\n\n${domainLink(d)} · ${own.length?`已有 ${own.length} 篇可读主题`:'核心正文仍在规划，领域导读提供边界与近邻入口'}\n\n${d.categories.map(c=>{const has=own.some(t=>t.category===c.id);return `- ${has?`[${c.title}](${categoryUrl(d,c)})`:c.title+'（规划）'}：${c.summary}`}).join('\n')}`}).join('\n\n')}\n\n目录不是完成度承诺。计划项不计入可读文章、搜索或完整路线；[内容方法与纠错](/about.html)说明版本与复核原则。`)
  for(const d of taxonomy){const own=topics.filter(t=>t.domain===d.id)
    page(`knowledge/${d.id}/index.md`,d.title,d.summary,`${d.summary}\n\n## 进入前与领域边界\n\n${d.prerequisites}\n\n${d.boundary}\n\n## 核心关系与阅读顺序\n\n${domainGuides[d.id].model}\n\n${domainGuides[d.id].order}\n\n常见误区：${domainGuides[d.id].mistake}\n\n**综合任务**：${domainGuides[d.id].task}\n\n## 从分类进入\n\n${d.categories.map(c=>{const children=own.filter(t=>t.category===c.id);return `### ${c.title}\n\n${c.summary}\n\n${children.length?`[分类导读](${categoryUrl(d,c)})\n\n${list(children)}`:'本分类正文仍在规划，当前不提供空文章链接。'}\n\n后续范围：${c.planned.join('、')}。`}).join('\n\n')}\n\n## 如何与其他领域连接\n\n${domainBridges[d.id]}`)
    for(const c of d.categories){const children=own.filter(t=>t.category===c.id);if(!children.length)continue;const guide=categoryGuides[d.id+'/'+c.id];if(!guide)throw Error('Missing category teaching guide: '+d.id+'/'+c.id)
      page(`knowledge/${d.id}/${c.id}/index.md`,c.title,c.summary,`[知识目录](/knowledge/) / ${domainLink(d)}\n\n${c.summary}\n\n## 阅读定位\n\n${guide.prerequisites}\n\n${guide.model}\n\n## 怎样选择阅读入口\n\n${guide.order}\n\n常见混淆：${guide.mistake}\n\n**小目标**：${guide.task}\n\n## 可读主题\n\n${list(children)}\n\n这里按问题查找，不把排列位置当作强先修。每篇的“理解先修”说明真正需要的知识及原因；路线只提供推荐的推进顺序。\n\n## 继续展开的范围\n\n${c.planned.join('、')}。这些是后续主题，未完成前不会产生空链接。`)
    }
  }
  page('paths/index.md','学习路线','围绕学习目标排列同一组知识点，区分阅读准备、推荐顺序与强先修。',`路线只安排阅读和任务，不拥有正文。你可以从领域目录直接进入知识点，也可以按这里的阶段推进；相邻两篇不自动构成强先修。\n\n${paths.map(p=>`## ${p.title}\n\n${p.goal}\n\n进入前：${p.entry.join('；')}。\n\n[查看路线与阶段任务](${sourceUrl(p.source)})`).join('\n\n')}\n\n## 路线草案\n\n${plannedPaths.map(p=>`- **${p.title}**：${p.goal}。${p.missing}。`).join('\n')}\n\n草案没有“开始完整课程”入口。已经知道某阶段结论时，可先完成它的任务；能给出条件和反例，再跳过对应阅读。`)
  for(const p of paths){page(p.source,p.title,p.goal,`${p.goal}\n\n## 阅读准备与可跳过条件 {#entry}\n\n${p.entry.join('；')}。这些是进入本路线的基础，不是要求先完成整站。\n\n已经熟悉一个阶段时，先尝试该阶段任务；若能说明成立条件、反例和未验证范围，可以跳过阅读。需要定位具体问题时，直接进入知识页。\n\n${p.stages.map((s,i)=>`## ${i+1}. ${s.title} {#stage-${i+1}}\n\n${s.transition}\n\n${s.readings.map(r=>{const t=topics.find(t=>t.id===r.topic);return `- ${link(t)}（${r.role==='required'?'主线':'选读'}）：${r.purpose}`}).join('\n')}\n\n**阶段任务**：${s.task}`).join('\n\n')}\n\n## 完成以后 {#completion}\n\n用一个改变条件的反例检查自己的解释，再比较两个都合理的方案。路线的完成不等于职位或能力认证；留下可复核的推理比记录读过多少页更有用。\n\n[实验与验证](/resources/experiments.html)提供完整源码、运行范围和历史记录；[复习与推理](/resources/review.html)按领域、类型与任务筛选问题。`)}
  page('cases/index.md','场景与排障','从可见问题选择证据，连接机制、方案与恢复责任。',`场景先定义业务目标和约束；排障先区分看起来相似的原因。它们都回链同一份机制知识，避免再维护一套简化答案。\n\n## 场景方案\n\n${list(topics.filter(t=>t.kind==='scenario'))}\n\n## 排障入口\n\n- [接口慢而数据库 CPU 不高：先查连接等待](/troubleshooting/connection-waiting.html)：区分未借到连接、持有连接做外部等待与 SQL 自身等待\n- [catch 住异常仍回滚](/knowledge/frameworks/spring-transactions/proxy-call-chain.html#shared-rollback)：检查异常经过的代理边界与共享回滚标记\n- [goroutine 收到取消仍未退出](/knowledge/go/concurrency/context-cancellation.html#worker-lifetime)：查停止条件、资源阻塞与等待责任\n- [缓存删过仍返回旧值](/knowledge/data/cache/invalidation-freshness.html#_2-后删也有窗口-旧读者还没回来)：追踪旧读者回填的时序\n- [已有去重记录却缺少投影](/knowledge/distributed/events/transactional-outbox.html#_3-消费去重的提交边界-比表名重要)：核对去重与副作用是否共同提交\n\n这些入口定位到真正的推理段落。需要全程练习时，再进入[学习路线](/paths/)。`)
  page('resources/source-reading.md','源码阅读','以输入、接收者、调用链和状态变化组织源码阅读。',`先写出想解释的外部行为，再固定版本、入口和输入。跟踪当前接收者是谁、为何分派到该实现、哪个分支修改了哪项状态；最后回到可见结果。\n\n## 已有源码主线\n\n${list(topics.filter(t=>t.kind==='source'||(t.tags.task||[]).includes('source-reading')))}\n\n## 一次阅读要留下什么\n\n1. 入口前后的输入与状态，而非整类代码截图\n2. 接口、抽象模板、实际实现与回调的角色\n3. 主链和关键条件；没有发生的分支单独说明\n4. 固定 tag/commit 的来源，以及 API 保证与当前实现的区别\n5. 一项改变输入后的预测；如果做了运行，另记环境和验证范围\n\n[实验与验证](/resources/experiments.html)区分源码复核和运行记录。代码块中的“示意”不等于上游原文，静态读懂一条分支也不等于已经运行全部路径。`)
  const rawRecords=registry.verification.filter(e=>e.legacyEvidence||(e.kind==='executed'&&e.status==='pass')).map(record=>({record,e:record.legacyEvidence?JSON.parse(readFileSync(join(root,record.legacyEvidence),'utf8')):{...record,versions:record.versions||[],notCovered:record.limitations,artifacts:(record.artifacts||[]).filter(a=>a.path.startsWith('docs/public/')).map(a=>({...a,path:a.path.replace('docs/public/','')}))}}))
  const records=groupExperimentRecords(rawRecords)
  page('resources/experiments.md','实验与验证','完整实验源、验证范围和可追溯版本，独立于文章编辑状态。',`实验用来区分两个解释：先预测，再安排时序、观察业务结果，最后改变一项条件。没有实验包的概念页也可以通过资料与源码复核；有运行记录的文章也不能据此宣称生产可靠。\n\n## 验证分别回答什么\n\n| 记录 | 支持的问题 | 不能自动推出 |\n| --- | --- | --- |\n| 资料与源码复核 | 合同、实现分支与版本 | 本机或生产已运行 |\n| 静态检查 | 语法、引用、图、片段一致性 | 业务执行结果 |\n| 进程内或单元运行 | 控制输入下的状态变化 | 真实依赖全部行为 |\n| 真实服务/进程运行 | 指定版本与故障模型下的观察 | 多节点、容量或生产保证 |\n\n每份记录另有未运行、通过、失败、受阻或过期状态。源码或参数变化后，需要重判旧证据是否仍适用；纯链接修改不伪装成一次新实验。\n\n## 可下载的完整实验\n\n${records.map(({record,e,ids})=>{const covered=topics.filter(t=>t.verificationRefs?.some(id=>ids.includes(id)));return `### ${experimentTitles[record.id]||record.title||record.id} {#experiment-${record.resourceGroup||record.id.replace(/^legacy\./,'').replaceAll('.','-')}}\n\n${e.artifacts.map(a=>`[${a.path.endsWith('.zip')?'下载源码包':a.path.endsWith('.py')?'下载完整模型':'查看运行结果'}](/${a.path})`).join(' · ')}。历史运行范围：${e.scope.join('；')}。\n\n关联知识：${covered.map(link).join('、')}。\n\n${record.id==='legacy.data-consistency'?'包内 NOT_RUN 是源码冻结时的历史说明；精确快照随后已执行，[2026-10-02 的验证摘要](/examples/data-consistency-verification.json)记录真实 MySQL/Redis 的范围与三条主动断线后的关闭警告。源码 ZIP 保持原身份；受控接收端并非真实 broker。\n\n':''}<details class="verification-appendix">\n<summary>版本、下载身份与未覆盖范围</summary>\n\n${e.versions.length?'- 版本：'+e.versions.join('；')+'\n':''}${e.artifacts.map(a=>`- SHA256：${a.sha256}`).join('\n')}\n- 未覆盖：${e.notCovered.join('；')}\n- 此处汇总已有运行记录；收录到目录不会增加实验覆盖范围\n\n</details>`}).join('\n\n')}\n\n## 自己运行前\n\n先阅读每个包的 README、版本和清理说明，使用隔离教学环境。不要把故障注入指向业务数据库；不要把凭据、真实用户资料或生产日志放进练习产物。运行失败时记录它实际失败的层次，不以“没有异常”替代业务结果。`)
  page('resources/review.md','复习与推理','按领域、文章类型与能力任务选择问题，答案回到同一知识主文。',`先不看原文，写下对象、状态与条件；再改变一项输入，解释结果为什么变化。这里的筛选帮助选择练习，不表示能力分数或面试频率。\n\n<TopicList mode="review" />`)
  page('tags.md','主题筛选','组合领域、类型与任务查找 canonical 知识点。',`分类表示主归属，标签表示技术、机制与任务。组合筛选不会复制正文；链接中的条件可以分享，浏览器前进后退会恢复选择。\n\n<TopicList />`)
  page('guide/knowledge-map.md','知识地图','目录、路线、场景和验证共享知识对象。',`知识目录把问题放回稳定领域，路线安排有目的的阅读，场景连接多个机制。它们共享主文；下面的箭头表示建议的理解顺序，真实强先修仍以每篇的原因说明为准。\n\n## 从局部关系开始\n\n- Java 对象相等性（独立专题规划） → ${topics.some(t=>t.id==='java.hashmap')?'[HashMap](/knowledge/java/collections/hashmap.html)':'HashMap（样板整合中）'} → 并发容器与缓存选型（规划）\n- [容器对象](/knowledge/frameworks/spring-container/bean-lifecycle.html) → [请求完成](/knowledge/frameworks/spring-mvc/request-pipeline.html) → [事务](/knowledge/frameworks/spring-transactions/proxy-call-chain.html)与[连接](/knowledge/frameworks/data-access/connection-budget.html) → [本地服务边界](/cases/orders/local-service-boundary.html)\n- [取消信号](/knowledge/go/concurrency/context-cancellation.html) → [工作退出与等待](/knowledge/go/concurrency/bounded-work.html) → [下游预算](/knowledge/go/http/client-budgets.html) → [进程排空](/knowledge/go/lifecycle/graceful-shutdown.html)\n- [库存不变量](/knowledge/data/transactions/inventory-invariants.html) → [幂等](/knowledge/distributed/reliable-interactions/idempotency.html) → [Outbox](/knowledge/distributed/events/transactional-outbox.html) → [缓存](/knowledge/data/cache/invalidation-freshness.html) → [联合恢复](/cases/orders/consistency-recovery.html)\n- [等待条件](/knowledge/foundations/operating-systems/blocking-waiting.html) → [结果与时序断言](/knowledge/foundations/testing/assertion-counterexamples.html) → [对象授权的反例](/knowledge/security/authorization/object-tenant-authorization.html#negative-tests)\n- [可信身份与撤销](/knowledge/security/authentication/authentication-boundaries.html) → [租户、对象与动作](/knowledge/security/authorization/object-tenant-authorization.html) → [身份与多租户路线](/paths/identity-tenancy.html)\n\n## 按领域定位\n\n${taxonomy.map(d=>`- ${domainLink(d)}：${d.summary}${topics.some(t=>t.domain===d.id)?'':'（机制正文仍在规划）'}`).join('\n')}\n\n## 跨过一个边界以后，为什么还要继续\n\n事务说明本地数据是否共同提交，却不保证响应必然送达，所以还需要幂等与结果查询。Outbox 保存待交接责任，却不能消除消费重投，所以要检查消费侧共同提交。取消通知工作不再等待，却不自动回收工作，所以要明确所有者和 join。\n\n[九域目录](/knowledge/)说明归属与内容状态；[学习路线](/paths/)说明阅读准备和阶段任务；[场景与排障](/cases/)从现象追踪责任。`)
  page('guide/practice.md','实验与评审的阅读入口','从问题、预测、观察和局限组织练习。',`练习要检验一个解释。先写预测，再安排输入和时序；如果结果不同，指出哪项假设被推翻。\n\n## 从一个具体知识点开始\n\n例如读 [context 的时序结果表](/knowledge/go/concurrency/context-cancellation.html#_2-跑实验-不要只断言一个-error)，先预测“副作用已发生后才取消”会留下什么。再运行相应源码，分别观察错误返回与 saved，而不是只检查函数有没有报错。最后改变一个条件，说明数据与返回策略哪一个变了。\n\n## 记录实验过程\n\n1. 要区分的解释与不允许破坏的业务合同\n2. 固定输入、环境与版本；教学替身和真实服务分开\n3. 正常路径与一项有区分力的错误实现\n4. 同时观察返回、业务事实和资源收尾\n5. 实际命令、结果和与预测不同的地方\n6. 清理、未覆盖条件与下一项验证\n\n这些记录帮助复现，不是用日志数量证明正确。没有执行的步骤明确写未运行，失败也不要改成一份预期输出。\n\n## 找到对应运行入口\n\n- [Spring 服务边界实验](/resources/experiments.html#experiment-spring-service-boundaries)：容器、MVC 与连接资源\n- [Go 服务生命周期实验](/resources/experiments.html#experiment-go-service-lifecycle)：HTTP、工作池、客户端和进程\n- [订单数据一致性实验](/resources/experiments.html#experiment-data-consistency)：库存、幂等、事件、缓存和恢复\n- [全部实验与固定版本](/resources/experiments.html)：包括独立事务、context、HashMap、定义注册及架构顺序模型\n\n运行前阅读该包的安全范围与清理说明，不将故障注入指向业务环境。\n\n## 比较选择与代价\n\n把目标与非目标、硬约束、最简单基线、两个备选方案以及失败后的动作写到同一页。用一个改变条件的例子解释何时应改选；涉及迁移时指出继续、停止与回退条件。\n\n[场景与排障](/cases/)提供完整任务，[复习与推理](/resources/review.html)帮助选择要检验的问题。通过本页练习不等于完成所有环境或获得某个职级。`)
  page('guide/roadmap.md','内容范围与规划','明确已发布知识、待补主题和不包含的产品功能。',`当前可读内容以[知识目录](/knowledge/)为准。每个领域说明边界，每个分类区分已有主题与后续范围；规划不会自动产生文章或完整路线。\n\n${plannedPaths.map(p=>`## ${p.title}\n\n${p.goal}。${p.missing}。`).join('\n\n')}\n\n## 身份与多租户\n\n[身份与多租户路线](/paths/identity-tenancy.html)已提供可信身份、撤销与对象授权的阅读主线。它的可运行示例是有限决策模型；真实身份供应商、密码学验证、多节点撤销和数据库授权执行仍需各自的证据。\n\n## 不以功能堆积替代学习\n\n本站暂不建设登录笔记、公司频次榜或厂商付费实验。来源、版本、机制图、源码主链、可复用路线和适用的验证优先。没有可靠统计，不展示学习提升百分比；没有目标环境证据，不标生产认证。`)
  page('about.md','关于与纠错','内容范围、来源、版本与维护方式。',`这里记录后端开发的机制与实践。文章围绕可以独立查找的问题组织；学习路线、源码与复习只提供不同入口。\n\n## 阅读约定\n\n- 概念页解释对象、条件和反例；模式页说明代价、替代与不适用条件\n- 源码结论固定到具体版本，公开 API 合同与实现细节分开\n- 实验只支持它明确运行的环境和故障模型；历史记录保留真实身份\n- 规划主题是编辑方向，不是已写完的文章或发布日期承诺\n\n## 来源与改进\n\n技术主张就近链接规范、官方文档或源码。图与说明自行组织，不把多个转载当作独立证据；引用代码按实际来源保留许可信息。\n\n发现错误时，可以通过页面的“编辑此页”进入仓库，或[提交问题](${site.repoUrl}/issues/new)。请带上页面、小节、涉及版本、观察与来源；不要提交凭据或生产个人数据。\n\n默认 VitePress 负责阅读与导航；Mermaid 在本地浏览器渲染，Code Hike 在构建时解析高亮与注解。没有第三方追踪、评论账户或付费解锁。`)
  for(const old of ['learn/index.md','learn/spring-service-boundaries/index.md','learn/go-service-lifecycle/index.md','learn/data-consistency/index.md'])if(existsSync(join(root,'docs',old)))unlinkSync(join(root,'docs',old))
  return topics
}
if(process.argv[1]?.endsWith('/generate-views.mjs'))console.log(`Generated views for ${generateViews().length} canonical topics`)
